#!/bin/bash
if [ ! -f 'options.cabal' ]; then
	echo -n "Can't find options.cabal; please run this script as"
	echo -n " ./scripts/run-tests from within the haskell-options source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_cabal_dev

# clean_dev_install

pushd tests
# rm -rf dist
$CABAL_DEV -s ../cabal-dev install || exit 1
popd

cabal-dev/bin/options_tests $@
