#!/bin/bash
if [ ! -f 'options.cabal' ]; then
	echo -n "Can't find options.cabal; please run this script as"
	echo -n " ./scripts/run-coverage from within the haskell-options source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_cabal_dev

pushd tests
$CABAL_DEV -s ../cabal-dev install --flags="coverage" || exit 1
popd

rm -f options_tests.tix
cabal-dev/bin/options_tests $@

EXCLUDES="\
--exclude=OptionsTests \
--exclude=OptionsTests.Defaults \
--exclude=OptionsTests.Help \
--exclude=OptionsTests.OptionTypes \
--exclude=OptionsTests.Tokenize \
--exclude=OptionsTests.StringParsing \
--exclude=Main"

hpc markup --srcdir=lib/ --srcdir=tests/ options_tests.tix --destdir=hpc-markup $EXCLUDES > /dev/null
hpc report --srcdir=lib/ --srcdir=tests/ options_tests.tix $EXCLUDES
